version: '2.15.1'
services:
  app:
    image: moviehub-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=moviehubpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=moviehub_database